FROM wordpress:php8.1-apache

# HAPUS SEMUA MPM (bukan disable lagi)
RUN rm -rf /etc/apache2/mods-enabled/mpm_* \
    && rm -rf /etc/apache2/mods-available/mpm_*

# BUAT CONFIG BARU HANYA PREFORK
RUN echo "LoadModule mpm_prefork_module /usr/lib/apache2/modules/mod_mpm_prefork.so" > /etc/apache2/mods-enabled/mpm_prefork.load

EXPOSE 80

CMD ["apache2-foreground"]
